### ISSUE TITLE
你好  你可不可以告诉我 你那个注意力机制部分的原理是来源于那篇论文呢

### ISSUE THREAD

**Issue by qiubeixiansheng** [ROBINADC/BiGRU-CRF-with-Attention-for-NER#2]

**Comment by qiubeixiansheng** [comment]
特别是“Cosine Attention”这一部分

**Comment by ROBINADC** [comment]
Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A.N., Kaiser, L.u., Polosukhin, I.: Attention is All you Need p. 11 (2017)

Luong, M.T., Pham, H., Manning, C.D.: Effective Approaches to Attention-based Neural Machine Translation. arXiv:1508.04025 [cs] (Sep 2015)

Graves, A., Wayne, G., Danihelka, I.: Neural Turing Machines. arXiv:1410.5401 [cs] (Dec 2014)

You can find cosine similarity in (Graves el al., 2014).

**Comment by qiubeixiansheng** [comment]
thanks
