### ISSUE TITLE
你好 ，我想问一下 ，  

### ISSUE THREAD

**Issue by qiubeixiansheng** [ROBINADC/BiGRU-CRF-with-Attention-for-NER#4]
“ if arg.use_pretrained_embeddings and all(map(os.path.exists, arg.embedding_paths)):
        pretrained_embeddings = load_embeddings(*arg.embedding_paths)
        model.init_embeddings(pretrained_embeddings, freeze=True)” 
这段代码是将word、char、pos向量链接为一个向量，这样做有什么好处？？链接好的向量是被送入到GRu层了么？？是怎么操作的呢

**Comment by ROBINADC** [comment]
We put different embeddings together to acquire a compllicated word representation, and anticipate that it can describe a word in more aspects. However, this is just an assignment, not a competitive setting.

The linked vector is then sent into the model, which serves as a normal embedding lookup table (`nn.Embedding`)
