### ISSUE TITLE
Question about Attention

### ISSUE THREAD

**Issue by karimmahalian** [ROBINADC/BiGRU-CRF-with-Attention-for-NER#5]
Hi,

Thank u for this great repo. I am a newbie to machine learning techniques, and I am trying to learn new things through different published codes like yours. Could u plz explain to me the difference between the different attention methods u used in your code is? Besides, did u try to combine all these methods to see if it enhances the performance or not? 

Thank u in advance

**Comment by ROBINADC** [comment]
Hi,

I am away from ML for some time. For the attention methods you mentioned, if you are referring to "the ways of computing the attentions", you can go to (Luong et al., 2015), which compared some of them. (Graves el al., 2014) also used cosine similarity in their research.
Besides, these methods cannot be combined as they are applied individually. The performance should vary with the context of different tasks.

Go luck !

Luong, M.T., Pham, H., Manning, C.D.: Effective Approaches to Attention-based Neural Machine Translation. arXiv:1508.04025 [cs] (Sep 2015)

Graves, A., Wayne, G., Danihelka, I.: Neural Turing Machines. arXiv:1410.5401 [cs] (Dec 2014)

**Comment by karimmahalian** [comment]
Hi,

thank u very much for ur answer. I have another question plz what does the cosine similarity function compute? 
Does it compare the current target hidden state with each source hidden state?
Do u have an explanation why cosine achieved better results than a scaled dot?

I apologize if I am disturbing you with these questions but I am trying to learn NLP with DL models and I am still struggling with tutorials and codes

**Comment by ROBINADC** [comment]
Hi,

Sorry for the late response.
Regarding why cosine got better results, I don't think there is a significant performance difference between the attention strategies I used in this particular task. The statistics are quite similar.
I hope you have figured out the other two questions in this month's time :) as they are nothing more than some formulas.

Thanks, and have a good time learning NLP !
