### ISSUE TITLE
attention weights

### ISSUE THREAD

**Issue by yassmine-lam** [ROBINADC/BiGRU-CRF-with-Attention-for-NER#6]
Hi,

I have a question about how scaled dot and cosine similarity are calculated

Given the current target hidden state qi with each source hidden state kj

The scaled dot is calculated as follows:

![Screen Shot 2021-09-22 at 7 29 47 AM](https://user-images.githubusercontent.com/75603019/134293784-d2661440-1983-49d9-b852-3f059e40af12.png)

where dw represents the dimension of word embeddings

The cosine similarity is computed as follows:

![Screen Shot 2021-09-22 at 7 30 58 AM](https://user-images.githubusercontent.com/75603019/134293896-379c3550-2bc6-4301-911e-9eab18ffc3dd.png)
 
Is that correct, or am I missing something?

Thank u in advance

**Comment by ROBINADC** [comment]
I figure these formulas are correct.
